<?xml version="1.0" encoding="UTF-8"?>
<p:procedure xmlns:a="http://www.aurora-framework.org/application" xmlns:p="uncertain.proc" trace="true">
    <!--<a:model-execute model="db.sys_mobile_pkg.login"/>
    <a:session-clear/>
    <a:session-write source="/session"/>
    <a:put-cookie name="JSID" value="${/session/@jsid}"/>--> 
    <a:model-execute model="db.sys_mobile_pkg.init_weixin_ticket"/>
    <p:echo/>   
</p:procedure>