<?xml version="1.0" encoding="UTF-8"?>
<p:procedure xmlns:a="http://www.aurora-framework.org/application" xmlns:p="uncertain.proc">
	<a:model-execute model="db.sys_login_pkg.ad_login"/>
	<a:session-clear/>
	<a:session-write source="/session"/>
	<a:session-write source="/parameter/@user_language" target="lang"/>-->
	<a:put-cookie name="JSID" value="${/parameter/@encrypted_session_id}"/>
	<a:put-cookie name="IS_NTLM" value="N"/>
	<p:echo/>
</p:procedure>